CREATE TABLE accounts
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(255)                            NOT NULL,
    address       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_accounts PRIMARY KEY (id)
);

ALTER TABLE accounts
    ADD CONSTRAINT uc_accounts_email UNIQUE (email);